# Read the Docs configuration file for envdot
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Set the OS, Python version, and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry or other tools if needed
      - pip install --upgrade pip

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Optionally build PDF & ePub
formats:
  - pdf
  - epub

# Python requirements for documentation
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - yaml

# Submodules configuration
submodules:
  include: all
  recursive: true